spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/print
    password: "19971230de"
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 80
